name: assety
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  firebase_analytics: ^11.3.3
  firebase_auth: ^5.3.1
  firebase_core: ^3.3.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  get_it: ^7.7.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.3
  injectable: ^2.4.2
  flutter_svg: ^2.0.10+1
  dio: ^5.7.0
  talker_flutter: ^4.3.2
  talker_dio_logger: ^4.3.2
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.4
  freezed: ^2.5.2
  cached_network_image: ^3.4.1
  url_launcher: ^6.2.6
dev_dependencies:
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
